# Use postgres/example user/password credentials
version: '3.1'

services:

  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - captain-overlay-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: Meme4321!
      POSTGRES_DB: hibernatedb
    ports:
      - 5432:5432

networks:
  captain-overlay-network:
    external: true