# Use postgres/example user/password credentials
version: '3.1'

services:

  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: Meme4321!
      POSTGRES_DB: hibernatedb
    ports:
      - 5432:5432
