# Use postgres/example user/password credentials
version: '3.8'

services:

  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "db"
    networks:
      - godinside

  db:
    container_name: postgres13
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: Meme4321!
      POSTGRES_DB: hibernatedb
    ports:
      - 5432:5432
    networks:
      - godinside

networks:
  godinside:
    name: godinside
